name: Webmailer CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Linter:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      # Cache Node.js modules
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint to check the project
      - name: Run ESLint
        run: npm run lint

  Tests_Unit_Integration:
    runs-on: ubuntu-latest
    needs: Linter

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      # Cache Node.js modules
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run unit tests using Jest
      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: npm run test:integration

  Docker_Deployment:
    runs-on: ubuntu-latest
    needs: Tests_Unit_Integration

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      # Cache Node.js modules
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Build the frontend
      - name: Build the frontend
        run: npm run build

      # Build the Docker image
      - name: Build the Docker image
        run: npm run docker:build

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      # Tag the Docker image
      - name: Tag the Docker image
        run: docker tag webmailer_image:latest "${{ secrets.DOCKER_USERNAME }}/webmailer:latest"

      # Push the Docker image
      - name: Push the Docker image
        run: docker push "${{ secrets.DOCKER_USERNAME }}/webmailer:latest"
